#include <QObject>
#include <QWidget>
#include "qhexspinbox.h"
#include "memsizewdgt.h"
#include "qhexedit/qhexedit.h"
#include "SocExplorerPlot.h"
#include "tcp_terminal_client.h"
#include "elf/elfparser.h"
#include "elf/abstractexecfile.h"
#include "elf/elffile.h"
#include "elf/elffilewidget.h"
